# Generated by Django 5.2.6 on 2025-12-05 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_alt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
